{% set version = "1.3.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-logr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/logr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/logr/logr_{{ version }}.tar.gz
  sha256: 5e1180b96e18a04069473cf124443fce39d8f6691c5461d6d0a9d981d42c3934

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-common
    - r-withr
  run:
    - r-base
    - r-common
    - r-withr

test:
  commands:
    - $R -e "library('logr')"           # [not win]
    - "\"%R%\" -e \"library('logr')\""  # [win]

about:
  home: https://logr.r-sassy.org
  dev_url: https://github.com/dbosak01/logr
  license: CC0-1.0
  summary: Contains functions to help create log files.  The package aims to overcome the difficulty of the base R sink() command.  The log_print() function will print to both the console and the file log, without interfering in other write operations.
  license_family: CC
  license_file:
    - LICENSE-CC0

extra:
  recipe-maintainers:
    - conda-forge/r
